db:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=xxxx
    volumes:
        - $HOME/docker/volumes/mysql/db:/var/lib/mysql
    ports:
        - "3306:3306"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:db
    ports:
        - "8080:80"
